### ISSUE TITLE
 please provide more detailed instructions for the deployment environment 

### ISSUE THREAD

**Issue by wk19921225** [AriaUI/Aria-UI#3]
Hello, I encountered the following issue while testing and running Aria-UI on my local machine:

#### Environment Information:
- Operating System: Ubuntu 24  
- Driver Version: 560.35.03  
- CUDA Version: 12.6  
- Python Version: 3.9  

#### Issue Description:
While installing `vllm` using the official command:

```bash
pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl
```

The installation log is as follows:

```plaintext
Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.20.3
    Uninstalling tokenizers-0.20.3:
      Successfully uninstalled tokenizers-0.20.3
  Attempting uninstall: transformers
    Found existing installation: transformers 4.45.0
    Uninstalling transformers-4.45.0:
      Successfully uninstalled transformers-4.45.0
Successfully installed tokenizers-0.21.0 transformers-4.48.0
```

The command uninstalls `transformers` and upgrades it to version 4.48.0, but the required version is 4.45.0. After the upgrade, I encountered the following parameter error:

```plaintext
ImportError: cannot import name 'LLAMA_ATTENTION_CLASSES' from 'transformers.models.llama.modeling_llama'
(/home/x/.pyenv/versions/aria-UI/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py)
```

Additionally, based on the provided installation command:

```bash
pip install https://vllm-wheels.s3.us-west-2.amazonaws.com/nightly/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl
```

I suspect that Python 3.8 is required. However, using Python 3.8 results in dependency errors.

#### Request:
Could you please provide more detailed instructions for the deployment environment to help resolve these issues? Thank you very much!

**Comment by AriaUI** [comment]
Hi,

Thanks for your feedback.

Can you try `vllm=0.6.3.dev83+g3d826d2c.d20241004`?

If it's truly the case, I'll modify the requirements to fix vllm at around 0.6.3 to prevent depending on later versions of transformers.

**Comment by AriaUI** [comment]
BTW, `transformers==4.45.1` works perfectly with `vllm=0.6.3.dev83+g3d826d2c.d20241004` on my machine.

**Comment by AriaUI** [comment]
Also, I suspect `Python 3.10` is required for Aria-series models. I'll add that into the instructions.

**Comment by Yahiy** [comment]
> Hi,
> 
> Thanks for your feedback.
> 
> Can you try `vllm=0.6.3.dev83+g3d826d2c.d20241004`?
> 
> If it's truly the case, I'll modify the requirements to fix vllm at around 0.6.3 to prevent depending on later versions of transformers.

Hi, can you share the link of vllm=0.6.3.dev83+g3d826d2c.d20241004, thanks.

I find the commit at https://github.com/vllm-project/vllm/tree/3d826d2c52242f4f78789adcb7c02938c84ed18b, but have anther bug:
`ValueError: Model architectures ['AriaForConditionalGeneration'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'ArcticForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'ExaoneForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'GraniteForCausalLM', 'GraniteMoeForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'JAISLMHeadModel', 'JambaForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MambaForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'MiniCPM3ForCausalLM', 'NemotronForCausalLM', 'OlmoForCausalLM', 'OlmoeForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi3SmallForCausalLM', 'PhiMoEForCausalLM', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'SolarForCausalLM', 'XverseForCausalLM', 'BartModel', 'BartForConditionalGeneration', 'MistralModel', 'Qwen2ForRewardModel', 'Gemma2Model', 'Blip2ForConditionalGeneration', 'ChameleonForConditionalGeneration', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'FuyuForCausalLM', 'InternVLChatModel', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'LlavaNextVideoForConditionalGeneration', 'LlavaOnevisionForConditionalGeneration', 'MiniCPMV', 'MolmoForCausalLM', 'NVLM_D', 'PaliGemmaForConditionalGeneration', 'Phi3VForCausalLM', 'PixtralForConditionalGeneration', 'QWenLMHeadModel', 'Qwen2VLForConditionalGeneration', 'UltravoxModel', 'MllamaForConditionalGeneration', 'EAGLEModel', 'MedusaModel', 'MLPSpeculatorPreTrainedModel']`

**Comment by AriaUI** [comment]
> > Hi,
> > Thanks for your feedback.
> > Can you try `vllm=0.6.3.dev83+g3d826d2c.d20241004`?
> > If it's truly the case, I'll modify the requirements to fix vllm at around 0.6.3 to prevent depending on later versions of transformers.
> 
> Hi, can you share the link of vllm=0.6.3.dev83+g3d826d2c.d20241004, thanks.
> 
> I find the commit at https://github.com/vllm-project/vllm/tree/3d826d2c52242f4f78789adcb7c02938c84ed18b, but have anther bug: `ValueError: Model architectures ['AriaForConditionalGeneration'] are not supported for now. Supported architectures: ['AquilaModel', 'AquilaForCausalLM', 'ArcticForCausalLM', 'BaiChuanForCausalLM', 'BaichuanForCausalLM', 'BloomForCausalLM', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeciLMForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'ExaoneForCausalLM', 'FalconForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTJForCausalLM', 'GPTNeoXForCausalLM', 'GraniteForCausalLM', 'GraniteMoeForCausalLM', 'InternLMForCausalLM', 'InternLM2ForCausalLM', 'JAISLMHeadModel', 'JambaForCausalLM', 'LlamaForCausalLM', 'LLaMAForCausalLM', 'MambaForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MptForCausalLM', 'MPTForCausalLM', 'MiniCPMForCausalLM', 'MiniCPM3ForCausalLM', 'NemotronForCausalLM', 'OlmoForCausalLM', 'OlmoeForCausalLM', 'OPTForCausalLM', 'OrionForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi3SmallForCausalLM', 'PhiMoEForCausalLM', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'RWForCausalLM', 'StableLMEpochForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'SolarForCausalLM', 'XverseForCausalLM', 'BartModel', 'BartForConditionalGeneration', 'MistralModel', 'Qwen2ForRewardModel', 'Gemma2Model', 'Blip2ForConditionalGeneration', 'ChameleonForConditionalGeneration', 'ChatGLMModel', 'ChatGLMForConditionalGeneration', 'FuyuForCausalLM', 'InternVLChatModel', 'LlavaForConditionalGeneration', 'LlavaNextForConditionalGeneration', 'LlavaNextVideoForConditionalGeneration', 'LlavaOnevisionForConditionalGeneration', 'MiniCPMV', 'MolmoForCausalLM', 'NVLM_D', 'PaliGemmaForConditionalGeneration', 'Phi3VForCausalLM', 'PixtralForConditionalGeneration', 'QWenLMHeadModel', 'Qwen2VLForConditionalGeneration', 'UltravoxModel', 'MllamaForConditionalGeneration', 'EAGLEModel', 'MedusaModel', 'MLPSpeculatorPreTrainedModel']`

Hi,

I just found I provided the wrong version..

Please use `vllm==0.6.6.dev3+g866fa455` + `transformers==4.48.0.dev0`.

The initial problem here centers around `transformers` rather than `vllm`. The latest version of `transformers` removes `LLAMA_ATTENTION_CLASSES ` from `https://github.com/huggingface/transformers/blob/241c04d36867259cdf11dbb4e9d9a60f9cb65ebc/src/transformers/models/llama/modeling_llama.py`, causing the error.

**A workaround could be re-installing `transformers==4.45.0` AFTER you've installed the latest vLLM.**

We'll work further to solve this issue smoothly. Stay tuned!
